/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { OnChainPaymentMethodPreviewResultAddressItem } from './OnChainPaymentMethodPreviewResultAddressItem';

export type OnChainPaymentMethodPreviewResultData = {
    /**
     * a list of addresses generated by the derivation scheme
     */
    addresses?: Array<OnChainPaymentMethodPreviewResultAddressItem>;
}
