/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type PaymentRequestBaseData = {
    /**
     * The amount of the payment request
     */
    amount?: string;
    /**
     * The title of the payment request
     */
    title?: string;
    /**
     * The currency of the payment request
     */
    currency?: string;
    /**
     * The email used in invoices generated by the payment request
     */
    email?: string | null;
    /**
     * The description of the payment request
     */
    description?: string | null;
    /**
     * The expiry date of the payment request
     */
    expiryDate?: string | null;
    /**
     * Custom CSS styling for the payment request
     */
    embeddedCSS?: string | null;
    /**
     * Custom CSS link for styling the payment request
     */
    customCSSLink?: string | null;
    /**
     * Whether to allow users to create invoices that partially pay the payment request
     */
    allowCustomPaymentAmounts?: boolean | null;
}
